/**
 * Static MauDau category list — slug → Ukrainian title + numeric portal_id
 * portal_id sourced from MauDau characteristics XML export (June 2026)
 */
export const MAUDAU_CATEGORIES_SEED: { slug: string; title: string; portal_id?: string }[] = [
  // Алкоголь
  { slug: 'alkohol-i-napoi', title: 'Алкоголь' },
  { slug: 'vyno', title: 'Вино' },
  { slug: 'vermuty', title: 'Вермути' },
  { slug: 'pyvo', title: 'Пиво' },
  { slug: 'ihrysti-vyna', title: 'Ігристі вина і шампанське' },
  { slug: 'mitsnyi-alkohol', title: 'Міцний алкоголь' },
  { slug: 'viski', title: 'Віскі' },
  { slug: 'brendi-i-koniak', title: 'Бренді і коньяк' },
  { slug: 'horilka', title: 'Горілка' },
  { slug: 'dzhyn', title: 'Джин' },
  { slug: 'rom', title: 'Ром' },
  { slug: 'tekila', title: 'Текіла і мескаль' },
  { slug: 'likery-i-nalyvky', title: 'Лікери і наливки' },
  { slug: 'nastoianky-balzamy-bittery', title: 'Настоянки, бальзами, біттери' },
  { slug: 'sake-i-aziiskyi-alkohol', title: 'Саке і азійський алкоголь' },
  { slug: 'bezalkoholni-ta-slaboalkoholni-napoi', title: 'Слабоалкогольні напої' },
  { slug: 'sydry-ta-medy', title: 'Сидри та меди' },
  { slug: 'podarunkovi-nabory-alkoholiu', title: 'Подарункові набори алкоголю' },
  // Продукти і напої
  { slug: 'produkty-kharchuvannia-ta-napoi', title: 'Продукти і напої' },
  { slug: 'bakaliia', title: 'Бакалія' },
  { slug: 'oliia-i-otset', title: 'Олія', portal_id: '536' },
  { slug: 'makaronni-vyroby', title: 'Макаронні вироби', portal_id: '533' },
  { slug: 'sukhi-snidanky', title: 'Сухі сніданки', portal_id: '539' },
  { slug: 'yizha-shvydkoho-pryhotuvannia', title: 'Їжа швидкого приготування', portal_id: '530' },
  { slug: 'spetsii-ta-prypravy', title: 'Спеції та приправи', portal_id: '538' },
  { slug: 'sil-tsukor', title: 'Цукор', portal_id: '540' },
  { slug: 'vse-dlia-vypichky', title: 'Все для випічки', portal_id: '542' },
  { slug: 'boroshno', title: 'Борошно', portal_id: '541' },
  { slug: 'pryprava-perets', title: 'Приправа перець', portal_id: '1199' },
  { slug: 'kukhonna-sil', title: 'Кухонна сіль', portal_id: '1068' },
  { slug: 'otset', title: 'Оцет', portal_id: '1070' },
  { slug: 'produkty-dlia-sushi-i-roliv', title: 'Продукти для суші і ролів', portal_id: '535' },
  { slug: 'zhele-ta-kysil', title: 'Желе та суміші для десертів', portal_id: '529' },
  { slug: 'krupy', title: 'Крупи' },
  { slug: 'rys', title: 'Рис', portal_id: '1182' },
  { slug: 'hrechana-krupa', title: 'Гречана крупа', portal_id: '1187' },
  { slug: 'vivsiana-krupa', title: 'Вівсяна крупа', portal_id: '1186' },
  { slug: 'bobovi', title: 'Бобові', portal_id: '1193' },
  { slug: 'kuskus', title: 'Кускус', portal_id: '1191' },
  { slug: 'bulhur', title: 'Булгур', portal_id: '1188' },
  { slug: 'pshenychna-krupa', title: 'Пшенична крупа', portal_id: '1185' },
  { slug: 'manna-krupa', title: 'Манна крупа', portal_id: '1190' },
  { slug: 'kinoa', title: 'Кіноа', portal_id: '1192' },
  { slug: 'kukurudziana-krupa', title: 'Кукурудзяна крупа', portal_id: '1184' },
  { slug: 'yachna-krupa', title: 'Ячна крупа', portal_id: '1189' },
  { slug: 'perlova-krupa', title: 'Перлова крупа', portal_id: '1183' },
  { slug: 'pshono', title: 'Пшоно', portal_id: '1468' },
  { slug: 'konservovani-produkty', title: 'Консервовані продукти' },
  { slug: 'miasni-ta-rybni-konservy', title: 'Рибні консерви', portal_id: '532' },
  { slug: 'ovochevi-ta-fruktovi-konservy', title: 'Овочева консервація', portal_id: '534' },
  { slug: 'miasni-konservy', title: 'М\'ясні консерви', portal_id: '1209' },
  { slug: 'fruktova-konservatsiia', title: 'Фруктова консервація', portal_id: '1230' },
  { slug: 'olyvky-ta-maslyny', title: 'Оливки та маслини', portal_id: '1220' },
  { slug: 'pashtety', title: 'Паштети', portal_id: '1208' },
  { slug: 'varennia-dzhemy-ta-med', title: 'Джеми', portal_id: '528' },
  { slug: 'konservovani-hryby', title: 'Консервовані гриби', portal_id: '1221' },
  { slug: 'med', title: 'Мед', portal_id: '1233' },
  { slug: 'varennia', title: 'Варення', portal_id: '1232' },
  { slug: 'sousy-i-marynady', title: 'Соуси і маринади' },
  { slug: 'sousy', title: 'Соуси', portal_id: '1215' },
  { slug: 'sousy-maionez-hirchytsia-khrin', title: 'Майонез', portal_id: '537' },
  { slug: 'ketchup', title: 'Кетчуп', portal_id: '1202' },
  { slug: 'tomatna-pasta', title: 'Томатна паста', portal_id: '1217' },
  { slug: 'hirchytsia', title: 'Гірчиця', portal_id: '1201' },
  { slug: 'marynady', title: 'Маринади', portal_id: '1212' },
  { slug: 'khrin', title: 'Хрін', portal_id: '1206' },
  { slug: 'kondyterski-vyroby', title: 'Кондитерські вироби' },
  { slug: 'shokolad', title: 'Шоколад', portal_id: '1235' },
  { slug: 'batonchyky', title: 'Батончики', portal_id: '1236' },
  { slug: 'pechyvo', title: 'Печиво', portal_id: '1228' },
  { slug: 'vafli', title: 'Вафлі', portal_id: '1237' },
  { slug: 'biskvity-ta-rulety', title: 'Бісквіти та рулети', portal_id: '1229' },
  { slug: 'kruasany-ta-rohalyky', title: 'Круасани та рогалики', portal_id: '1231' },
  { slug: 'prianyky', title: 'Пряники', portal_id: '1226' },
  { slug: 'horikhovi-pasty', title: 'Пасти горіхові', portal_id: '1065' },
  { slug: 'zhuvalna-humka', title: 'Жувальна гумка', portal_id: '553' },
  { slug: 'drazhe-ta-lodianyky', title: 'Драже та льодяники', portal_id: '1244' },
  { slug: 'zhuvalni-tsukerky', title: 'Жувальні цукерки', portal_id: '1245' },
  { slug: 'zefir-ta-marshmelou', title: 'Зефір та маршмелоу', portal_id: '1063' },
  { slug: 'marmelad', title: 'Мармелад', portal_id: '1200' },
  { slug: 'keksy-ta-panetone', title: 'Кекси та панетоне', portal_id: '1227' },
  { slug: 'tistechka', title: 'Тістечка', portal_id: '1239' },
  { slug: 'torty', title: 'Торти', portal_id: '1238' },
  { slug: 'korzhi-dlia-torta', title: 'Коржі для торта', portal_id: '1872' },
  { slug: 'hariachi-napoi', title: 'Гарячі напої' },
  { slug: 'kava', title: 'Кава', portal_id: '544' },
  { slug: 'kakao-hariachyi-shokolad-tsykorii', title: 'Какао', portal_id: '545' },
  { slug: 'chai-2', title: 'Чай', portal_id: '546' },
  { slug: 'sneky', title: 'Снеки' },
  { slug: 'chipsy', title: 'Чипси', portal_id: '562' },
  { slug: 'sukharyky-ta-hrinky', title: 'Сухарики та грінки', portal_id: '558' },
  { slug: 'horikhy-ta-sukhofrukty', title: 'Горіхи', portal_id: '559' },
  { slug: 'sneky-miasni', title: 'М\'ясні снеки', portal_id: '567' },
  { slug: 'sneky-rybni', title: 'Рибні снеки', portal_id: '561' },
  { slug: 'nasinnia-2', title: 'Насіння', portal_id: '1198' },
  { slug: 'sukhofrukty', title: 'Сухофрукти', portal_id: '1196' },
  { slug: 'popkorn', title: 'Попкорн', portal_id: '1197' },
  { slug: 'kukurudziani-palychky-popkorn', title: 'Кукурудзяні палички', portal_id: '560' },
  { slug: 'susheni-hryby', title: 'Сушені гриби', portal_id: '1669' },
  { slug: 'syrni-zakusky', title: 'Сирні закуски', portal_id: '2124' },
  { slug: 'khlibtsi', title: 'Хлібці', portal_id: '563' },
  { slug: 'hrysini', title: 'Грисіні', portal_id: '1204' },
  { slug: 'solomka', title: 'Соломка', portal_id: '1210' },
  { slug: 'sushky', title: 'Сушки', portal_id: '1211' },
  { slug: 'sukhari', title: 'Сухарі', portal_id: '1213' },
  { slug: 'tartaletky', title: 'Тарталетки', portal_id: '1214' },
  { slug: 'tosty', title: 'Тості', portal_id: '1216' },
  { slug: 'napoi', title: 'Напої' },
  { slug: 'soky', title: 'Соки та нектари', portal_id: '548' },
  { slug: 'voda', title: 'Вода', portal_id: '549' },
  { slug: 'solodka-voda', title: 'Солодка вода', portal_id: '550' },
  { slug: 'enerhetychni-napoi', title: 'Енергетичні напої', portal_id: '612' },
  { slug: 'molochni-produkty', title: 'Молочні продукти' },
  { slug: 'moloko', title: 'Молоко', portal_id: '1222' },
  { slug: 'roslynne-moloko', title: 'Рослинне молоко', portal_id: '1224' },
  { slug: 'zghushchene-moloko', title: 'Згущене молоко', portal_id: '1302' },
  { slug: 'syry', title: 'Сири', portal_id: '1749' },
  { slug: 'vershkove-maslo', title: 'Вершкове масло', portal_id: '2371' },
  { slug: 'khlibobulochni-vyroby', title: 'Хлібобулочні вироби' },
  { slug: 'bulochky', title: 'Булочки', portal_id: '1828' },
  { slug: 'lavashi-ta-tortyli', title: 'Лаваші та тортильї', portal_id: '1829' },
  { slug: 'khlib', title: 'Хліб', portal_id: '1874' },
  { slug: 'napivfabrykaty', title: 'Напівфабрикати' },
  { slug: 'ovochevi-napivfabrykaty', title: 'Овочеві напівфабрикати', portal_id: '2514' },
  { slug: 'rybni-napivfabrykaty', title: 'Рибні напівфабрикати', portal_id: '2532' },
  { slug: 'miasni-napivfabrykaty', title: 'М\'ясні напівфабрикати', portal_id: '2535' },
  { slug: 'fruktovi-napivfabrykaty', title: 'Фруктові напівфабрикати', portal_id: '2534' },
  { slug: 'zamorozheni-i-okholodzheni-hotovi-stravy', title: 'Заморожені і охолоджені готові страви', portal_id: '2536' },
  { slug: 'kartopliani-napivfabrykaty', title: 'Картопляні напівфабрикати', portal_id: '2537' },
  { slug: 'zamorozheni-i-okholodzheni-tisto-ta-vypichka', title: 'Заморожені і охолоджені тісто та випічка', portal_id: '2538' },
  { slug: 'zamorozheni-i-okholodzheni-moreprodukty', title: 'Заморожені і охолоджені морепродукти', portal_id: '2540' },
  { slug: 'superfudy', title: 'Суперфуди', portal_id: '1121' },
  { slug: 'sublimovani-produkty', title: 'Сублімовані продукти', portal_id: '1776' },
  { slug: 'kovbasy', title: 'Ковбаси', portal_id: '1985' },
  { slug: 'syrovyna-dlia-vyrobnytstva-alkoholiu', title: 'Сировина для виробництва алкоголю' },
  // Товари для барбекю
  { slug: 'tovary-dlia-barbekiu-ta-piknika', title: 'Товари для барбекю та пікніка' },
  { slug: 'vugillia-ta-aksesuari-dlya-rozpalyuvannya', title: 'Вугілля та аксесуари для розпалювання' },
  // Спортивне харчування
  { slug: 'sportyvne-kharchuvannia', title: 'Спортивне харчування' },
  // Дитяче харчування
  { slug: 'dytiache-kharchuvannia', title: 'Дитяче харчування' },
]
