/**
 * Static MauDau category list — slug → Ukrainian title
 * Sourced from maudau.com.ua navigation (June 2026)
 */
export const MAUDAU_CATEGORIES_SEED: { slug: string; title: string }[] = [
  // Алкоголь
  { slug: 'alkohol-i-napoi', title: 'Алкоголь' },
  { slug: 'vyno', title: 'Вино' },
  { slug: 'vermuty', title: 'Вермути' },
  { slug: 'pyvo', title: 'Пиво' },
  { slug: 'ihrysti-vyna', title: 'Ігристі вина і шампанське' },
  { slug: 'mitsnyi-alkohol', title: 'Міцний алкоголь' },
  { slug: 'viski', title: 'Віскі' },
  { slug: 'brendi-i-koniak', title: 'Бренді і коньяк' },
  { slug: 'horilka', title: 'Горілка' },
  { slug: 'dzhyn', title: 'Джин' },
  { slug: 'rom', title: 'Ром' },
  { slug: 'tekila', title: 'Текіла і мескаль' },
  { slug: 'likery-i-nalyvky', title: 'Лікери і наливки' },
  { slug: 'nastoianky-balzamy-bittery', title: 'Настоянки, бальзами, біттери' },
  { slug: 'sake-i-aziiskyi-alkohol', title: 'Саке і азійський алкоголь' },
  { slug: 'bezalkoholni-ta-slaboalkoholni-napoi', title: 'Слабоалкогольні напої' },
  { slug: 'sydry-ta-medy', title: 'Сидри та меди' },
  { slug: 'podarunkovi-nabory-alkoholiu', title: 'Подарункові набори алкоголю' },
  // Продукти і напої
  { slug: 'produkty-kharchuvannia-ta-napoi', title: 'Продукти і напої' },
  { slug: 'bakaliia', title: 'Бакалія' },
  { slug: 'oliia-i-otset', title: 'Олія' },
  { slug: 'makaronni-vyroby', title: 'Макаронні вироби' },
  { slug: 'sukhi-snidanky', title: 'Сухі сніданки' },
  { slug: 'yizha-shvydkoho-pryhotuvannia', title: 'Їжа швидкого приготування' },
  { slug: 'spetsii-ta-prypravy', title: 'Спеції та приправи' },
  { slug: 'sil-tsukor', title: 'Цукор' },
  { slug: 'vse-dlia-vypichky', title: 'Все для випічки' },
  { slug: 'boroshno', title: 'Борошно' },
  { slug: 'pryprava-perets', title: 'Приправа перець' },
  { slug: 'kukhonna-sil', title: 'Кухонна сіль' },
  { slug: 'otset', title: 'Оцет' },
  { slug: 'produkty-dlia-sushi-i-roliv', title: 'Продукти для суші і ролів' },
  { slug: 'zhele-ta-kysil', title: 'Желе та суміші для десертів' },
  { slug: 'krupy', title: 'Крупи' },
  { slug: 'rys', title: 'Рис' },
  { slug: 'hrechana-krupa', title: 'Гречана крупа' },
  { slug: 'vivsiana-krupa', title: 'Вівсяна крупа' },
  { slug: 'bobovi', title: 'Бобові' },
  { slug: 'kuskus', title: 'Кускус' },
  { slug: 'bulhur', title: 'Булгур' },
  { slug: 'pshenychna-krupa', title: 'Пшенична крупа' },
  { slug: 'manna-krupa', title: 'Манна крупа' },
  { slug: 'kinoa', title: 'Кіноа' },
  { slug: 'kukurudziana-krupa', title: 'Кукурудзяна крупа' },
  { slug: 'yachna-krupa', title: 'Ячна крупа' },
  { slug: 'perlova-krupa', title: 'Перлова крупа' },
  { slug: 'pshono', title: 'Пшоно' },
  { slug: 'konservovani-produkty', title: 'Консервовані продукти' },
  { slug: 'miasni-ta-rybni-konservy', title: 'Рибні консерви' },
  { slug: 'ovochevi-ta-fruktovi-konservy', title: 'Овочева консервація' },
  { slug: 'miasni-konservy', title: 'М\'ясні консерви' },
  { slug: 'fruktova-konservatsiia', title: 'Фруктова консервація' },
  { slug: 'olyvky-ta-maslyny', title: 'Оливки та маслини' },
  { slug: 'pashtety', title: 'Паштети' },
  { slug: 'varennia-dzhemy-ta-med', title: 'Джеми' },
  { slug: 'konservovani-hryby', title: 'Консервовані гриби' },
  { slug: 'med', title: 'Мед' },
  { slug: 'varennia', title: 'Варення' },
  { slug: 'sousy-i-marynady', title: 'Соуси і маринади' },
  { slug: 'sousy', title: 'Соуси' },
  { slug: 'sousy-maionez-hirchytsia-khrin', title: 'Майонез' },
  { slug: 'ketchup', title: 'Кетчуп' },
  { slug: 'tomatna-pasta', title: 'Томатна паста' },
  { slug: 'hirchytsia', title: 'Гірчиця' },
  { slug: 'marynady', title: 'Маринади' },
  { slug: 'khrin', title: 'Хрін' },
  { slug: 'kondyterski-vyroby', title: 'Кондитерські вироби' },
  { slug: 'shokolad', title: 'Шоколад' },
  { slug: 'batonchyky', title: 'Батончики' },
  { slug: 'pechyvo', title: 'Печиво' },
  { slug: 'vafli', title: 'Вафлі' },
  { slug: 'biskvity-ta-rulety', title: 'Бісквіти та рулети' },
  { slug: 'kruasany-ta-rohalyky', title: 'Круасани та рогалики' },
  { slug: 'prianyky', title: 'Пряники' },
  { slug: 'horikhovi-pasty', title: 'Пасти горіхові' },
  { slug: 'zhuvalna-humka', title: 'Жувальна гумка' },
  { slug: 'drazhe-ta-lodianyky', title: 'Драже та льодяники' },
  { slug: 'zhuvalni-tsukerky', title: 'Жувальні цукерки' },
  { slug: 'zefir-ta-marshmelou', title: 'Зефір та маршмелоу' },
  { slug: 'marmelad', title: 'Мармелад' },
  { slug: 'keksy-ta-panetone', title: 'Кекси та панетоне' },
  { slug: 'tistechka', title: 'Тістечка' },
  { slug: 'torty', title: 'Торти' },
  { slug: 'korzhi-dlia-torta', title: 'Коржі для торта' },
  { slug: 'hariachi-napoi', title: 'Гарячі напої' },
  { slug: 'kava', title: 'Кава' },
  { slug: 'kakao-hariachyi-shokolad-tsykorii', title: 'Какао' },
  { slug: 'chai-2', title: 'Чай' },
  { slug: 'sneky', title: 'Снеки' },
  { slug: 'chipsy', title: 'Чипси' },
  { slug: 'sukharyky-ta-hrinky', title: 'Сухарики та грінки' },
  { slug: 'horikhy-ta-sukhofrukty', title: 'Горіхи' },
  { slug: 'sneky-miasni', title: 'М\'ясні снеки' },
  { slug: 'sneky-rybni', title: 'Рибні снеки' },
  { slug: 'nasinnia-2', title: 'Насіння' },
  { slug: 'sukhofrukty', title: 'Сухофрукти' },
  { slug: 'popkorn', title: 'Попкорн' },
  { slug: 'kukurudziani-palychky-popkorn', title: 'Кукурудзяні палички' },
  { slug: 'susheni-hryby', title: 'Сушені гриби' },
  { slug: 'syrni-zakusky', title: 'Сирні закуски' },
  { slug: 'napoi', title: 'Напої' },
  { slug: 'soky', title: 'Соки та нектари' },
  { slug: 'voda', title: 'Вода' },
  { slug: 'solodka-voda', title: 'Солодка вода' },
  { slug: 'enerhetychni-napoi', title: 'Енергетичні напої' },
  { slug: 'molochni-produkty', title: 'Молочні продукти' },
  { slug: 'moloko', title: 'Молоко' },
  { slug: 'roslynne-moloko', title: 'Рослинне молоко' },
  { slug: 'zghushchene-moloko', title: 'Згущене молоко' },
  { slug: 'syry', title: 'Сири' },
  { slug: 'vershkove-maslo', title: 'Вершкове масло' },
  { slug: 'khlibobulochni-vyroby', title: 'Хлібобулочні вироби' },
  { slug: 'khlibtsi', title: 'Хлібці' },
  { slug: 'hrysini', title: 'Грисіні' },
  { slug: 'solomka', title: 'Соломка' },
  { slug: 'sushky', title: 'Сушки' },
  { slug: 'sukhari', title: 'Сухарі' },
  { slug: 'tartaletky', title: 'Тарталетки' },
  { slug: 'tosty', title: 'Тості' },
  { slug: 'bulochky', title: 'Булочки' },
  { slug: 'lavashi-ta-tortyli', title: 'Лаваші та тортильї' },
  { slug: 'khlib', title: 'Хліб' },
  { slug: 'napivfabrykaty', title: 'Напівфабрикати' },
  { slug: 'ovochevi-napivfabrykaty', title: 'Овочеві напівфабрикати' },
  { slug: 'rybni-napivfabrykaty', title: 'Рибні напівфабрикати' },
  { slug: 'miasni-napivfabrykaty', title: 'М\'ясні напівфабрикати' },
  { slug: 'fruktovi-napivfabrykaty', title: 'Фруктові напівфабрикати' },
  { slug: 'zamorozheni-i-okholodzheni-hotovi-stravy', title: 'Заморожені і охолоджені готові страви' },
  { slug: 'kartopliani-napivfabrykaty', title: 'Картопляні напівфабрикати' },
  { slug: 'zamorozheni-i-okholodzheni-tisto-ta-vypichka', title: 'Заморожені і охолоджені тісто та випічка' },
  { slug: 'zamorozheni-i-okholodzheni-moreprodukty', title: 'Заморожені і охолоджені морепродукти' },
  { slug: 'superfudy', title: 'Суперфуди' },
  { slug: 'sublimovani-produkty', title: 'Сублімовані продукти' },
  { slug: 'kovbasy', title: 'Ковбаси' },
  { slug: 'syrovyna-dlia-vyrobnytstva-alkoholiu', title: 'Сировина для виробництва алкоголю' },
  // Товари для барбекю
  { slug: 'tovary-dlia-barbekiu-ta-piknika', title: 'Товари для барбекю та пікніка' },
  { slug: 'vugillia-ta-aksesuari-dlya-rozpalyuvannya', title: 'Вугілля та аксесуари для розпалювання' },
  // Спортивне харчування
  { slug: 'sportyvne-kharchuvannia', title: 'Спортивне харчування' },
  // Дитяче харчування
  { slug: 'dytiache-kharchuvannia', title: 'Дитяче харчування' },
]
